name: auto-merge

on:
  pull_request_target:
    types:
    - opened
    - reopened
    - synchronize
    branches:
    - main

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
    - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@ccfb013c15c8afb7bf2b7c028fb74dc5a068cccc  # 1.3.4
      with:
        ref: ${{ github.ref }}
        check-name: build
        wait-interval: 10
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Enable auto-merge for Dependabot PRs
      run: gh pr merge --auto --squash ${{ github.event.pull_request.html_url }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
