name: website

# build the documentation whenever there are new commits on main
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '20 20 * * 1'
  push:
    branches:
      - main
    # Alternative: only build for tags.
    # tags:
    #   - '*'

# security: restrict permissions for CI jobs.
permissions:
  contents: read

# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mhils/workflows/checkout@v13
      - uses: mhils/workflows/setup-python@v13
      - uses: mhils/workflows/setup-uv@v13
      - run: uv run make.py

      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
