name: autofix.ci
on: [ push, pull_request ]
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo fmt
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
