name: autofix.ci
on:
  workflow_call:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # Use uv to ensure we have the same ruff version in CI and locally.
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          version: "0.4.20"
      # Fix lint errors
      - run: uv run ruff check --fix-only .
      # Format code
      - run: uv run ruff format .

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
